# Generated by Django 2.0.2 on 2018-06-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='')),
                ('bedrooms', models.IntegerField()),
                ('category', models.ManyToManyField(to='rental.Category')),
            ],
        ),
    ]
