# Generated by Django 2.0.2 on 2018-06-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='category',
            new_name='categories',
        ),
    ]
