# Generated by Django 2.0.2 on 2018-07-14 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20180623_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='конструкция дома')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='районы')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='период постройки')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rental',
            name='owner',
        ),
        migrations.AddField(
            model_name='rental',
            name='residential_square',
            field=models.PositiveIntegerField(default=0, verbose_name='жилая квадратура'),
        ),
        migrations.AddField(
            model_name='rental',
            name='storeys',
            field=models.PositiveIntegerField(default=0, verbose_name='этажность дома'),
        ),
        migrations.AddField(
            model_name='rental',
            name='total_square',
            field=models.PositiveIntegerField(default=0, verbose_name='общая квадратура'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=150, verbose_name='категории'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='количество комнат'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='categories',
            field=models.ManyToManyField(to='rental.Category', verbose_name='категории'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='city',
            field=models.CharField(max_length=150, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='description',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='title',
            field=models.CharField(max_length=150, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='rental',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.Design', verbose_name='конструкция дома'),
        ),
        migrations.AddField(
            model_name='rental',
            name='districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.District', verbose_name='районы'),
        ),
        migrations.AddField(
            model_name='rental',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.Period', verbose_name='период постройки'),
        ),
    ]
