# Generated by Django 2.0.2 on 2018-07-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20180714_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='rental',
            name='design',
        ),
        migrations.AddField(
            model_name='rental',
            name='design',
            field=models.ManyToManyField(null=True, to='rental.Design', verbose_name='конструкция дома'),
        ),
    ]
