# Generated by Django 2.0.2 on 2018-07-14 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_auto_20180714_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='design',
            options={'verbose_name': 'конструкция', 'verbose_name_plural': 'конструкции'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'район', 'verbose_name_plural': 'районы'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'период постройки', 'verbose_name_plural': 'периоды постройки'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'дом', 'verbose_name_plural': 'дома'},
        ),
        migrations.RemoveField(
            model_name='rental',
            name='city',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=150, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='design',
            field=models.ManyToManyField(to='rental.Design', verbose_name='конструкции дома'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.District', verbose_name='район'),
        ),
    ]
