# Generated by Django 2.0.2 on 2018-07-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20180714_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='districts',
            new_name='district',
        ),
    ]
